### ISSUE TITLE
Dados do Processo - Atualizar data de hoje

### ISSUE THREAD

**Issue by taynaraginacio** [codigodamata/codigodamata#19]
Atualizar data da minuta para que ela corresponda à data de hoje. 

![image](https://user-images.githubusercontent.com/71410583/118419814-7e479400-b693-11eb-83bd-9713674a105c.png)

**Comment by lucasdeor** [comment]
O problema está na variável que foi utilizada "data_hoje", pois ela já está predefinida. Sendo assim, mesmo que eu set default: ${ today(format='M/d/YYYY') }, ainda aparece a 10/01/2020
Precisamos fazer uma limpeza geral, em todo o código ao que tange a utilização de datas, substituindo pelo vocabulário próprio do docassemble e discriminando variáveis que são de input de usuário das auxiliares, por exemplo, as de tempo.

**Comment by lucasdeor** [comment]
Alterar também "Data do fato" em "Descrição do caso (descrição fática)"

**Comment by lucasdeor** [comment]
Correção realizada no #25
