### ISSUE TITLE
Criar lista com estados

### ISSUE THREAD

**Issue by lucasdeor** [codigodamata/codigodamata#34]
Criar lista com sigla dos estados para adicionar nas entrevistas com formato dropdown

**Comment by lucasdeor** [comment]
Feito, porém há uma diferença de design entre o combobox e dropdown (que aparecem um ao lado do outro) que incomoda

**Comment by lucasdeor** [comment]
Mudança se encontra na qualificação do requerido, porem há mais um outro local em que precisamos mudar também.

**Comment by ViniciusPansini** [comment]
Aprovado, parabéns!

**Comment by rvnovaes** [comment]
@ViniciusPansini passar para um arquivo em separado chamado comum_lista_estados.yml

**Comment by ViniciusPansini** [comment]
Foi criado um novo arquivo chamado comum_lista_estados.yml com a função lista_estados() e foi substituído nos arquivos em que é necessária a lista com os estados do Brasil.

**Comment by lucasdeor** [comment]
Aprovado
